#!/bin/bash
#
# Transform EM or segmentations in EM space to LM space for the ROI2 image of a TCell

# ARGUMENTS
imageN5="$1"            # The n5 base directory holding image data
inputDataset="$2"       # The input n5 datseet
outputDataset="$3"      # The output dataset


# non-deformable parts of the registration
BASEDIR=$(dirname "$0")
xfm="${BASEDIR}/bigwarpLandmarks.csv"
nm2um="${BASEDIR}/nmToum.mat"

# https://github.com/saalfeldlab/template-building/blob/master/scripts/sparkTransformN5
sparkTransformN5 3 \
    -n $imageN5 \
    -i $inputDataset \
    -o $outputDataset \
    -s $outSz \
    -p "8,0,0,0,0,8,0,0,0,0,8,0" \
    -r "8,8,8" \
    -t ${nm2um} \
    -t $xfm \
    -t ${nm2um}?i \

